//
// Created by kendricks on 12/17/23.
//

#ifndef UNITS_H
#define UNITS_H

#define UNITS_CONST_POINTER_CONST(TYPE) const TYPE* const


#define UNITS_MAGINITUDE_TYPE long double
#define UNITS_MAGINITUDE_TYPE_ZERO 0.0L
#define UNITS_STR_TO_MAGNITUDE_TYPE(STR) atof(STR)
#define UNITS_MAGINITUDE_TYPE_IS_ZERO(A) ((A) == 0)
#define UNITS_MAGINITUDE_TYPE_ADD(A,B) ((A) + (B))
#define UNITS_MAGINITUDE_TYPE_SUBTRACT(A,B) ((A) - (B))
#define UNITS_MAGINITUDE_TYPE_MULTIPLY(A,B) ((A) * (B))
#define UNITS_MAGINITUDE_TYPE_MODULO(A,B) ((A) % (B))
#define UNITS_MAGINITUDE_TYPE_DIVIDE(A,B) ((A) / (B))
#define UNITS_MAGNITUDE_TYPE_TO_STRING(STR,A) sprintf(STR,"%Lf", (A))
#define UNITS_TO_LARGEST_UNSIGNED_INTEGER(A) (size_t)(A)
#define UNITS_TO_LARGEST_SIGNED_INTEGER(A) ((ptrdiff_t)(A))
#define UNITS_MAX_NUMBER_OF_CHARACTERS_IN_STRING 1000
#define UNITS_TO_LARGEST_REAL_NUMBER(A) ((long double)(A))
#define UNITS_FREE_UNITS_MAGINITUDE_TYPE(UNIT)

#endif //UNITS_H
